apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: order-service-canary-analysis
  namespace: fiveline
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      failureLimit: 1
      successCondition: result[0] <= 10.0
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              sum(rate(http_requests_total{namespace="fiveline",job=~".*order-service.*",status_code=~"5.."}[2m]))
              /
              sum(rate(http_requests_total{namespace="fiveline",job=~".*order-service.*"}[2m]))
            ) * 100 or vector(0)
