apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - service-canary.yaml
  - analysis-template.yaml
  - hpa.yaml
  - pdb.yaml
  - service-monitor.yaml

images:
  - name: 089955620282.dkr.ecr.ap-northeast-2.amazonaws.com/fiveline/order-service
    newTag: dev-111-55901f68618f64ff80a425e7e919b2d95c695c7f
