apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: fiveline
  labels:
    app: order-service
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::089955620282:role/fiveline-order-service-sa-role
