apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: 089955620282.dkr.ecr.ap-northeast-2.amazonaws.com/fiveline/product-service
    newTag: dev-41-2903db8494b5e665df5e6b13bb08f0c7d17b7a4a
