apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: 089955620282.dkr.ecr.ap-northeast-2.amazonaws.com/fiveline/product-service
    newTag: dev-49-f80e295c9f2dbf166ef0f2fc4ac568b3d5472614
