apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: fiveline
  labels:
    app: product-service
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::089955620282:role/fiveline-product-service-sa-role
