apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiveline-external-secret
  namespace: fiveline
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 60m

  secretStoreRef:
    name: fiveline-aws-sm
    kind: ClusterSecretStore

  target:
    name: fiveline-secret
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiveline/app/db-credential
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: fiveline/app/jwt-signing-key
        property: JWT_SECRET
    - secretKey: REDIS_URL
      remoteRef:
        key: fiveline/app/redis-credential
        property: REDIS_URL
