apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: 089955620282.dkr.ecr.ap-northeast-2.amazonaws.com/fiveline/user-service
    newTag: latest
