apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: fiveline
  labels:
    app: user-service
  # IRSA 어노테이션은 보안 담당자 IAM Role 생성 후 추가
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::089955620282:role/fiveline-user-service-sa-role
