apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiveline-ingress
  namespace: fiveline
  labels:
    project: fiveline
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-name: fiveline-alb
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/subnets: subnet-0578ca7e0de9d6f3c,subnet-0e818a84ee982022d
    # ACM/WAF는 보안 담당자 작업 후 아래 주석 해제
    # alb.ingress.kubernetes.io/certificate-arn: <ACM_CERT_ARN>
    # alb.ingress.kubernetes.io/ssl-redirect: "443"
    # alb.ingress.kubernetes.io/wafv2-web-acl-arn: <WAF_REGIONAL_ARN>
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8001
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8001
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8002
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8003
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8003
          - path: /api/health
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8001
