apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiveline

resources:
  - namespace.yaml
  - external-secrets/
  - user-service/
  - product-service/
  - order-service/
  - admin-service/
  - network-policy/
