apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

images:
  - name: 089955620282.dkr.ecr.ap-northeast-2.amazonaws.com/fiveline/admin-service
    newTag: latest
