apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service-sa
  namespace: fiveline
  labels:
    app: admin-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::089955620282:role/fiveline-admin-service-sa-role
